baseURL: https://pollydrive.github.io/schola
languageCode: ru-ru
title: schola
theme: "PaperMod"

params:
  homeInfoParams:
    Title: σχολή (schola) – «досуг, свободное времяпровождение»
    Content: Тут можно найти кружки по интересам, единомышленников и учителей

  socialIcons: # optional
    - name: "youtube"
      url: "https://www.youtube.com/channel/UCfdvqLvTzcyw6iRnHq-JQZA"
    - name: "telegram"
      url: "https://t.me/PollyDrive"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Polly"
  contact: "@PollyDrive"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

 #Google Analytics 4 optional
  env: #production
  GoogleAnalytics: "G-00000XXXXX" 
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Категории кружков 
      url: /categories/
      weight: 10
    - identifier: tags
      name: Кураторы
      url: /tags/
      weight: 20
    - identifier: search
      name: Поиск
      url: /search/
      weight: 20
    - identifier: archive
      name: Архив
      url: /archives/
      weight: 20
